# Database schema containing the data
db_config:
  schema: crdppf
  topickey: idobj
  srid: 2056

  tables:
    # table containing the municipality or cadastral boundaries : NE = cadastres
    town:
      tablename: la02_cadastres
     # tablename: la3_limites_communales
      schema: general
      # primary key
      att_id: idobj
      # optional - if subdivision in cadastres :
      att_cadastre_number: numcad
      # optional - if subdivision in cadastres :
      att_cadastre_name: cadnom
      att_commune_number: numcom
      att_commune_name: comnom
      att_federal_number: nufeco
    # table containing the properties
    property:
      tablename: mo9_immeubles
      schema: mensuration
      att_id: idobj
      att_id_property: id
      att_egrid: egrid
      att_property_number: nummai
      att_property_area: srfmai
      att_property_type: typimm
      #att_property_source: source
    #optional:
    local_names:
      tablename: mo25_noms_locaux
      schema: mensuration
      att_id: idcnlo
      att_local_name: nomloc

  restrictions:
      railways_project_zones
      railways_construction_limits
      highways_project_zones
      highways_construction_limits
      road_construction_limits
      airport_security_zones
      airport_project_zones
      airport_construction_limits
      military_polluted_sites
      airport_polluted_sites
      transportation_polluted_sites
      road_noise
      forest_limits
      forest_distances
